linters:
  disable-all: true
  enable:
    - deadcode
    - dupl
    - godot
    - goimports
    - gosimple
    - ineffassign
    - misspell
    - revive
    - structcheck
    - typecheck
    - unused
    - varcheck